### ISSUE TITLE
ErrorException in AbstractWrapper.php line 575: Undefined offset: 1

### ISSUE THREAD

**Issue by stefanmahr** [faustbrian/Laravel-Sofort#5]
- Version: 1.10
- PHP Version: 7.0.1

Hallo,

I have tried to setup your example and get the following error. Maybe you can help me?

`ErrorException in AbstractWrapper.php line 575: Undefined offset: 1`

Best greetings

**Comment by faustbrian** [comment]
Your auth key has to look like this `userId:projectId:apiKey` or the Sofortüberweisung library will fail to parse your key.

The official Sofortüberweisung library parses your key like this `list($this->_userId, $this->_projectId, $this->_apiKey) = explode(':', $configKey);` and will throw the exception you get if your key doesn't have the right format.
